# This is a basic workflow to help you get started with Actions

name: Sync Fork

# Controls when the action will run. 
on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:  # click the button on Github repo!


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  sync_with_upstream:
    runs-on: ubuntu-latest
    name: Sync main with upstream latest

    steps:
      - uses: tgymnich/fork-sync@v1.4
        with:
          base: deploy
          head: deploy
